// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkPermitManagement.Data;

namespace WorkPermitManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220706141022_firstMigration")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WorkPermitManagement.Models.WorkPermit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NaturalAdvantage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("activity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("function")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("otherAdavantages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("salaryInNumbers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("salaryInWords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("socialSecurityNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("taxIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("WorkPermit");
                });
#pragma warning restore 612, 618
        }
    }
}
