// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkPermitManagement.Data;

namespace WorkPermitManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220707201722_updateDB")]
    partial class updateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WorkPermitManagement.Models.WorkPermit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CODE_AVANT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CODE_CONT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CODE_DEM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CODE_REGIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONT_ACTIVITE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONT_ACTIVITE_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("CONT_CARTE_SEJOUR")
                        .HasColumnType("tinyint");

                    b.Property<string>("CONT_CAT_ENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONT_CODE_ACT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONT_CODE_CAS_SOC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONT_CODE_CONTRAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONT_CODE_DELEG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONT_CODE_ENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CONT_CODE_PERS")
                        .HasColumnType("int");

                    b.Property<string>("CONT_CODE_SIT_MAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONT_CREATED_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CONT_DATE_DEBUT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CONT_DATE_ENVOI_DR")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CONT_DATE_FIN")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CONT_DATE_PAIE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CONT_DATE_RESILIATION")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CONT_DATE_SAISIE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CONT_EMPLOYEUR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONT_EMPLOYEUR_ADR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONT_EMPLOYEUR_ADR_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONT_EMPLOYEUR_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("CONT_EST_RESILIE")
                        .HasColumnType("tinyint");

                    b.Property<int>("CONT_ETAT_PAIE")
                        .HasColumnType("int");

                    b.Property<string>("CONT_FONCTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONT_FONCTION_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CONT_MODE_PAIE")
                        .HasColumnType("int");

                    b.Property<string>("CONT_NATIONALITE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONT_NATIONALITE_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CONT_NATURE_CONTRAT")
                        .HasColumnType("int");

                    b.Property<string>("CONT_NUM_CNSS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONT_OBS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONT_PASSEPORT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONT_PERSONNE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONT_PERSONNE_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONT_QRCODE_AR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONT_QRCODE_FR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONT_REF_PAIE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CONT_SALAIRE")
                        .HasColumnType("float");

                    b.Property<string>("CONT_SIGNER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONT_SIGNER_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CONT_UPDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CONT_UPDATED_BY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CONT_VAL_LOGEMENT")
                        .HasColumnType("float");

                    b.Property<double>("CONT_VAL_NOURRITURE")
                        .HasColumnType("float");

                    b.Property<DateTime>("DATE_LIVRAISON")
                        .HasColumnType("datetime2");

                    b.Property<int>("synched")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("WorkPermit");
                });
#pragma warning restore 612, 618
        }
    }
}
